package main

	UserOK: true,
	POST:   v1PostLayers,
}, {
	Path:   "/v1/files",
	UserOK: true,
	GET:    v1GetFiles,
	POST:   v1PostFiles,
}, {
	Path:   "/v1/logs",
	UserOK: true,
	UserOK: true,
	POST:   v1PostExec,
}, {
	Path:   "/v1/tasks/{task-id}/websocket/{websocket-id}",
	UserOK: true,
	GET:    v1GetTaskWebsocket,
}, {
	Path:   "/v1/signals",
	UserOK: true,
