package main

package cmd

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"strings"
	"time"

	"entgo.io/contrib/entgql"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	sentryhttp "github.com/getsentry/sentry-go/http"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	_ "github.com/lib/pq"
	"github.com/rs/cors"
	"github.com/rs/zerolog/log"
			AllowCredentials: true,
			Debug:            os.Getenv("DEBUG") == "true",
		}).Handler)

		router.Use(middleware.Timeout(60*time.Second), middleware.RealIP)
		router.Use(api.AuthzByPolicyMiddleware)
		router.Use(api.AuthenticationMiddleware)
		if os.Getenv("DEBUG") == "true" {
			router.Use(api.LoggingMiddleware)
		}

		if os.Getenv("DEBUG_PPROF") == "true" {
			router.Mount("/debug", middleware.Profiler())
		}

		// Limit the request body size for all requests to the
		// This is based on the chi middleware.RequestSize. Way this middleware is
		// added to the router to use it
		// https://github.com/go-chi/chi/blob/master/middleware/request_size.go
		router.Use(func(h http.Handler) http.Handler {
			fn := func(w http.ResponseWriter, r *http.Request) {

				// When image transfer is enabled, the request body size is limited.
				// This is done to prevent the server from being overloaded by large
				// DoS attack over the network.
				const _50KB = (1 << 10) * 50

				limitedBody := http.MaxBytesReader(w, r.Body, _50KB)
				bodyBytes, err := ioutil.ReadAll(limitedBody)
				limitedBody.Close()

				// if r.Body reach the max size limit, the request will be canceled
				// and the error will be returned to the client
				if r.ContentLength > _50KB || err != nil {
					http.Error(w, http.StatusText(http.StatusRequestEntityTooLarge), http.StatusRequestEntityTooLarge)
					return
				}

				r.Body = ioutil.NopCloser(bytes.NewBuffer(bodyBytes))
				h.ServeHTTP(w, r)
			}
			return http.HandlerFunc(fn)
		})

		if *playgroudActive {
			router.Handle("/", playground.Handler("GraphQL playground", "/graphql"))
			log.Info().Msgf("connect to http://localhost:%s/ for GraphQL playground", *apiPortFlag)

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.28

import (
	"context"
	"github.com/rs/zerolog/log"
)

// CreateFriendship is the resolver for the createFriendship field.
func (r *mutationResolver) CreateFriendship(ctx context.Context, userID uuid.UUID) (bool, error) {
	cu, err := CurrentUserFromContext(ctx)
	if err != nil {
	return true, nil
}

// DeleteFriendship is the resolver for the deleteFriendship field.
func (r *mutationResolver) DeleteFriendship(ctx context.Context, userID uuid.UUID) (bool, error) {
	cu, err := CurrentUserFromContext(ctx)
	if err != nil {
	return true, nil
}

// CreateOrUpdateFollowsGroup is the resolver for the createOrUpdateFollowsGroup field.
func (r *mutationResolver) CreateOrUpdateFollowsGroup(ctx context.Context, input typesgen.FollowsGroupInput) (*generated.FollowsGroup, error) {
	cu, err := CurrentUserFromContext(ctx)
	if err != nil {
	return fg, nil
}

// DeleteFollowsGroup is the resolver for the deleteFollowsGroup field.
func (r *mutationResolver) DeleteFollowsGroup(ctx context.Context, id uuid.UUID) (bool, error) {
	cu, err := CurrentUserFromContext(ctx)
	if err != nil {
	return true, nil
}

// AssignFollowsGroupToUser is the resolver for the assignFollowsGroupToUser field.
func (r *mutationResolver) AssignFollowsGroupToUser(ctx context.Context, userID uuid.UUID, followsGroupID uuid.UUID, assign bool) (bool, error) {
	// Get the current user from the context
	cu, err := CurrentUserFromContext(ctx)
	return true, nil
}

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input typesgen.SettingsInput) (*gotype.Settings, error) {
	cu, err := CurrentUserFromContext(ctx)
	if err != nil {
	return &updatedUser.Settings, nil
}

// InternalCreateUser is the resolver for the internalCreateUser field.
func (r *mutationResolver) InternalCreateUser(ctx context.Context, input typesgen.CreateUserInput) (uuid.UUID, error) {
	campusID, err := r.client.Campus.Query().Where(campus.DuoID(input.CurrentDuoCampusID)).FirstID(ctx)
	if err != nil {
		ID(ctx)
}

// InternalLinkAccount is the resolver for the internalLinkAccount field.
func (r *mutationResolver) InternalLinkAccount(ctx context.Context, input typesgen.LinkAccountInput) (*generated.Account, error) {
	id, err := r.client.Account.Create().
		SetProvider(input.Provider.String()).
	return account, nil
}

// InviteOnDiscord is the resolver for the inviteOnDiscord field.
func (r *mutationResolver) InviteOnDiscord(ctx context.Context) (bool, error) {
	cu, err := CurrentUserFromContext(ctx)
	if err != nil {
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*generated.User, error) {
	return CurrentUserFromContext(ctx)
}

// SearchUser is the resolver for the searchUser field.
func (r *queryResolver) SearchUser(ctx context.Context, query string, onlyOnline *bool) ([]*generated.User, error) {
	usersID, err := searchengine.NewClient().SearchUser(query, *onlyOnline)
	if err != nil {
	}).All(ctx)
}

// Campus is the resolver for the campus field.
func (r *queryResolver) Campus(ctx context.Context, id uuid.UUID) (*generated.Campus, error) {
	return r.client.Campus.Query().Where(campus.ID(id)).Only(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*generated.User, error) {
	return r.client.User.Query().Where(user.ID(id)).Only(ctx)
}

// Location is the resolver for the location field.
func (r *queryResolver) Location(ctx context.Context, id uuid.UUID) (*generated.Location, error) {
	return r.client.Location.Query().Where(location.ID(id)).Only(ctx)
}

// Locations is the resolver for the locations field.
func (r *queryResolver) Locations(ctx context.Context, page typesgen.PageInput, campusID uuid.UUID) (*generated.LocationConnection, error) {
	return r.client.Location.Query().
		Where(location.CampusID(campusID)).
		Paginate(ctx, page.After, &page.First, page.Before, page.Last)
}

// LocationsByCampusName is the resolver for the locationsByCampusName field.
func (r *queryResolver) LocationsByCampusName(ctx context.Context, page typesgen.PageInput, campusName string) (*generated.LocationConnection, error) {
	return r.client.Campus.Query().
		Where(campus.Name(campusName)).
		Paginate(ctx, page.After, &page.First, page.Before, page.Last)
}

// LocationsByCluster is the resolver for the locationsByCluster field.
func (r *queryResolver) LocationsByCluster(ctx context.Context, page typesgen.PageInput, campusName string, identifierPrefix *string) (*generated.LocationConnection, error) {
	return r.client.Campus.Query().
		Where(campus.NameEqualFold(campusName)).
		Paginate(ctx, page.After, &page.First, page.Before, page.Last)
}

// LocationsStatsByPrefixes is the resolver for the locationsStatsByPrefixes field.
func (r *queryResolver) LocationsStatsByPrefixes(ctx context.Context, campusName string, identifierPrefixes []string) ([]*typesgen.LocationStats, error) {
	sqlResults := []*typesgen.LocationStats{}
	prefixes := make([]any, len(identifierPrefixes))
	return finalLocationStats, err
}

// MyFollowings is the resolver for the myFollowings field.
func (r *queryResolver) MyFollowings(ctx context.Context, followsGroupID *uuid.UUID, followsGroupSlug *string) ([]*generated.User, error) {
	cu, _ := CurrentUserFromContext(ctx)

		All(ctx)
}

// MyFollowsGroups is the resolver for the myFollowsGroups field.
func (r *queryResolver) MyFollowsGroups(ctx context.Context) ([]*generated.FollowsGroup, error) {
	cu, _ := CurrentUserFromContext(ctx)

		All(ctx)
}

// FollowsGroupsForUser is the resolver for the followsGroupsForUser field.
func (r *queryResolver) FollowsGroupsForUser(ctx context.Context, userID uuid.UUID) ([]*generated.FollowsGroup, error) {
	// Get the current user from the context
	cu, err := CurrentUserFromContext(ctx)
		All(ctx)
}

// InternalGetUserByAccount is the resolver for the internalGetUserByAccount field.
func (r *queryResolver) InternalGetUserByAccount(ctx context.Context, provider typesgen.Provider, uid string) (*generated.User, error) {
	return r.client.Account.Query().
		Where(account.Provider(provider.String()), account.ProviderAccountID(uid)).
		Only(ctx)
}

// InternalGetUserByEmail is the resolver for the internalGetUserByEmail field.
func (r *queryResolver) InternalGetUserByEmail(ctx context.Context, email string) (*generated.User, error) {
	return r.client.User.Query().
		Where(user.Email(email)).
		Only(ctx)
}

// InternalGetUser is the resolver for the internalGetUser field.
func (r *queryResolver) InternalGetUser(ctx context.Context, id uuid.UUID) (*generated.User, error) {
	return r.client.User.Get(ctx, id)
}

// IsSwimmer is the resolver for the isSwimmer field.
func (r *userResolver) IsSwimmer(ctx context.Context, obj *generated.User) (bool, error) {
	if obj.PoolYear == nil || obj.PoolMonth == nil {
		return false, nil
		strings.EqualFold(*obj.PoolMonth, now.Format("January"))), nil
}

// IsMe is the resolver for the isMe field.
func (r *userResolver) IsMe(ctx context.Context, obj *generated.User) (bool, error) {
	cu, _ := CurrentUserFromContext(ctx)

	return cu.ID == obj.ID, nil
}

// IsFollowing is the resolver for the isFollowing field.
func (r *userResolver) IsFollowing(ctx context.Context, obj *generated.User) (bool, error) {
	cu, _ := CurrentUserFromContext(ctx)

	return false, nil
}

// IsFollower is the resolver for the isFollower field.
func (r *userResolver) IsFollower(ctx context.Context, obj *generated.User) (bool, error) {
	cu, _ := CurrentUserFromContext(ctx)

	"net/http"

	sentryhttp "github.com/getsentry/sentry-go/http"
	"github.com/go-chi/chi/v5"
	"github.com/rs/cors"
	"github.com/rs/zerolog/log"
)
